Feature/storage data
Revolution-Populi/revpop-core pull request #91
Opened 2022-01-17 09:43 UTC by GoodWien

2022-01-19 11:21 UTC, tedthecreator requested changes
Take a look at the `/libraries/protocol/custom_authorities/sliced_lists.hxx`

2022-01-19 11:21 UTC, tedthecreator commented on libraries/chain/content_card_evaluator.cpp
> +   if (HARDFORK_REVPOP_15_PASSED(fc::time_point_sec(fc::time_point::now())))
`if (HARDFORK_REVPOP_15_PASSED(head_block_time()))`

2022-01-19 11:21 UTC, tedthecreator commented on libraries/chain/content_card_evaluator.cpp
> +   if (HARDFORK_REVPOP_15_PASSED(fc::time_point_sec(fc::time_point::now())))
if (HARDFORK_REVPOP_15_PASSED(head_block_time()))

2022-01-19 11:21 UTC, tedthecreator commented on libraries/chain/personal_data_evaluator.cpp
> +   if (HARDFORK_REVPOP_15_PASSED(fc::time_point_sec(fc::time_point::now())))
`if (HARDFORK_REVPOP_15_PASSED(head_block_time()))`

2022-01-19 14:16 UTC, GoodWien commented on libraries/chain/content_card_evaluator.cpp
> +   if (HARDFORK_REVPOP_15_PASSED(fc::time_point_sec(fc::time_point::now())))
Done.

2022-01-19 14:16 UTC, GoodWien commented on libraries/chain/content_card_evaluator.cpp
> +   if (HARDFORK_REVPOP_15_PASSED(fc::time_point_sec(fc::time_point::now())))
Done.

2022-01-19 14:16 UTC, GoodWien commented on libraries/chain/personal_data_evaluator.cpp
> +   if (HARDFORK_REVPOP_15_PASSED(fc::time_point_sec(fc::time_point::now())))
Done.

2022-01-21 14:10 UTC, tedthecreator approved these changes

2022-01-21 14:18 UTC, merged